package main

//
// a word-count application "plugin" for MapReduce.
//
// go build -buildmode=plugin wc.go
//

import "6.824/mr"
import "unicode"
import "strings"
import "strconv"

//
// The map function is called once for each file of input. The first
// argument is the name of the input file, and the second is the
// file's complete contents. You should ignore the input file name,
// and look only at the contents argument. The return value is a slice
// of key/value pairs.
//
func Map(filename string, contents string) []mr.KeyValue {
	// function to detect word separators.
	/* 不是字母 */
	ff := func(r rune) bool { return !unicode.IsLetter(r) }

	// split contents into an array of words.
	/* 分割单词 */
	words := strings.FieldsFunc(contents, ff)

	kva := []mr.KeyValue{}
	// [{aa 1} {bb 1} {cc 1} {d 1} {ee 1} {ff 1} {aa 1} {cc 1}]
	for _, w := range words {
		kv := mr.KeyValue{w, "1"}
		kva = append(kva, kv)
	}
	return kva
}

//
// The reduce function is called once for each key generated by the
// map tasks, with a list of all the values created for that key by
// any map task.
//
func Reduce(key string, values []string) string {
	// return the number of occurrences of this word.
	/* 由于这个字符串数组里面都是 "1"  所以我们只需要计算数组的长度就好 */
	return strconv.Itoa(len(values))
}
